
export interface CalendarEventData {
  summary: string;
  description?: string;
  location?: string;
  startTime: string; // ISO string
  endTime: string; // ISO string
}

// Stored in LocalStorage to give context to Gemini about what we've already booked
export interface LocalEventRecord extends CalendarEventData {
  localId: string; // UUID generated by us
  gcalId: string; // Google Calendar Event ID
  lastUpdated: string; // ISO string
  originalText?: string; // The user's original raw text
  synced: boolean; // Whether it was successfully pushed to Google Calendar
  error?: string; // Last error message if sync failed
}

export enum ActionType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  MOVE = 'MOVE', // New: Move from another calendar to managed calendar
  IGNORE = 'IGNORE',
}

export interface ProposedAction {
  type: ActionType;
  confidenceScore: number;
  reasoning: string;
  eventData?: CalendarEventData;
  targetLocalId?: string; // If UPDATE, which local ID are we modifying?
  
  // For Move Logic
  sourceCalendarId?: string;
  sourceEventId?: string;
}

// The raw response from Gemini
export interface GeminiResponse {
  actions: ProposedAction[];
}

export type AIProvider = 'GEMINI' | 'OPENAI';

export interface AIConfig {
  provider: AIProvider;
  apiKey: string;
  baseUrl?: string;
  model?: string;
}

export interface GoogleCalendar {
  id: string;
  summary: string;
  primary?: boolean;
}
