export interface CalendarEventData {
  summary: string;
  description?: string;
  location?: string;
  startTime: string; // ISO string
  endTime: string; // ISO string
}

// Stored in LocalStorage to give context to Gemini about what we've already booked
export interface LocalEventRecord extends CalendarEventData {
  localId: string; // UUID generated by us
  gcalId: string; // Google Calendar Event ID
  lastUpdated: string; // ISO string
}

export enum ActionType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  IGNORE = 'IGNORE',
}

export interface ProposedAction {
  type: ActionType;
  confidenceScore: number;
  reasoning: string;
  eventData?: CalendarEventData;
  targetLocalId?: string; // If UPDATE, which local ID are we modifying?
}

// The raw response from Gemini
export interface GeminiResponse {
  actions: ProposedAction[];
}
